### ISSUE TITLE
Auctions Item based query does not work properly

### ISSUE THREAD

**Issue by skyblockz** [slothpixel/core#291]
When you give time param (from / until) to skyblock/auctions it doesnt return properly
The things I typed for query : https://prnt.sc/ql93a9
The things I got for return: https://prnt.sc/ql93db

**Comment by builder-247** [comment]
Your UNIX timestamp has 1 extra digit, using a tool like https://www.epochconverter.com/ is a good idea to check every now and then.

On that note, I discovered a bug where the until parameter was being improperly assigned. It's now been fixed in https://github.com/slothpixel/core/commit/5fce9989338be4655dbd4d2dec29fed542a760c5 and deployed.
