### ISSUE TITLE
Skyblock Bazaar and Item discrepancies

### ISSUE THREAD

**Issue by MoSadie** [slothpixel/core#475]
I am using the skyblock/items endpoint to look up friendly names for items on the Bazaar. I noticed that 3 of the bazaar product ids from the Hypixel API did not match the information available on skyblock/items:
- ENCHANTED_CARROT_ON_A_STICK shows in skyblock/items as ENCHANTED_CARROT_STICK
- CATALYST does not appear on skyblock/items
- ENCHANTED_BONE_BLOCK does not appear on skyblock/items

Are these known issues and if not could we get those added to skyblock/items?

**Comment by builder-247** [comment]
Hello!

We currently generate the data show on `/items` endpoint from auction data, which causese most of these discrepancies. At the moment however we have to manually run updates due to database maintenance, which is why `ENCHANTED_BONE_BLOCK` doesn't appear for instance.

In the following days I'll make some adjustements to the system - include items like catalyst that can't be auctioned, as well as add/update the enchanted carrot on a stick item (I believe they switched IDs) and the way bazaar items are handled.

Thank you for bringing these issues to our attention!
