### ISSUE TITLE
Update method for detecting latest skyblock profile

### ISSUE THREAD

**Issue by builder-247** [slothpixel/core#761]
Update this function
https://github.com/slothpixel/core/blob/master/store/buildSkyBlockProfiles.js#L10-L13

to use the new `selected` property

**Comment by Bhav00** [comment]
I would like to work on this issue but I am a beginner. Can I have some context as to what this 'selected' property mentioned is?

**Comment by builder-247** [comment]
> I would like to work on this issue but I am a beginner. Can I have some context as to what this 'selected' property mentioned is?

Hello, each profile has a boolean value `selected` so here you need to just find one that has it as `true`.

**Comment by Bhav00** [comment]
> Hello, each profile has a boolean value `selected` so here you need to just find one that has it as `true`.

I think 
#### return Object.entries(profiles).find(item => item.members[uuid].selected == true); 
should do the thing, otherwise just `item.selected == true` if the `selected` is in the outermost  part of the object instead of inside `members[uuid]`.
If my approach is correct then I would like you to assign this problem to me. Otherwise, please correct me where I am wrong.

**Comment by builder-247** [comment]
This should do  it:
```js
Object.entries(profiles).find((profile) => profiles[profile].selected)
```

**Comment by Bhav00** [comment]
> This should do it:
> 
> ```js
> Object.entries(profiles).find((profile) => profiles[profile].selected)
> ```

So basically `Object.entries(profiles)` makes an array of arrays of profiles and the objects related to each profile, but the 'find' acts on the 'key' instead of accessing the 'values' and applying the constraints on it. Hence, as we need to access the object's 'selected' bool value, we use profiles[profile] to access the data stored, right?
I have made a pull request with the said change. And removed the `uuid` parameter from the function and it's call as well as it was not being used in any way in the function.

**Comment by builder-247** [comment]
Closed via https://github.com/slothpixel/core/commit/3ab87836c571589429af2f53687a742b2f068e0c.

**Comment by Bhav00** [comment]
Thank you for the guidance.
